# Generated by Django 5.1.7 on 2025-03-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoo",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todoo",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
